# Generated by Django 4.1.7 on 2023-05-11 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='bus_stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adminapp.busstops'),
        ),
        migrations.AddField(
            model_name='livedata',
            name='live_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
