# Generated by Django 4.1.7 on 2023-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_bus_name_livedata_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedata',
            name='bvoc',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='co2',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='humidity',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='iaq',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='pressure',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='temperature',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
