# Generated by Django 4.1.7 on 2023-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_livedata_bus_stop_alter_livedata_bvoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='device_eui',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='livedata',
            name='frame_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
